# Generated by Django 5.0.4 on 2024-04-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_food_options_food_created_food_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='about',
            field=models.CharField(default='description', max_length=300),
            preserve_default=False,
        ),
    ]
