# Generated by Django 5.0.4 on 2024-04-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_food_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_arrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('published_date', models.CharField(max_length=255)),
                ('description', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
        migrations.RemoveField(
            model_name='food',
            name='created',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated',
        ),
    ]
