# Generated by Django 5.0.4 on 2024-04-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_new_arrivals_description_new_arrivals_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_arrivals',
            old_name='about',
            new_name='description',
        ),
    ]
