# Generated by Django 5.0.4 on 2024-04-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_arriv_delete_new_arrivals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='arriv',
        ),
    ]
