# Generated by Django 5.0.4 on 2024-04-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_book_food_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
    ]
