# Generated by Django 5.0.4 on 2024-04-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_book_options_book_created_at_book_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
