# Generated by Django 5.0.4 on 2024-04-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_deals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deals',
            old_name='price',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='deals',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
