# Generated by Django 5.0.4 on 2024-04-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_deals_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='genre',
            field=models.TextField(choices=[('horror', 'horror'), ('romance', 'romance'), ('crime', 'crime'), ('Dark fantasy', 'Dark fantasy')], max_length=300),
        ),
    ]
